Add reduced parameter grids
knightlab-analyses/regression-benchmarking pull request #17
Opened 2020-08-17 22:07 UTC by gwarmstrong

I have added or updated the reduced parameter grids for the following regression algorithms:

* RandomForestRegressor
* KNeighborsRegressor
* ElasticNet
* Lasso
* Ridge
* Linear Regression
* MLPRegressor

And the following classification algorithms:
* KNeighborsClassifier
* LogisticRegression
* MLPClassifier
* RandomForestClassifier
* RidgeClassifier

2020-08-17 22:07 UTC, gwarmstrong commented
@patrickimran

2020-08-20 19:23 UTC, gwarmstrong commented on q2_mlab/tests/test_parameters.py
> +        "RidgeRegressor",
@patrickimran the grids you added should be added to these class variables so those grids can be tested.

2020-08-21 00:03 UTC, gwarmstrong commented on .travis.yml
>    - conda env create -q -n test-env --file qiime2-latest-py36-linux-conda.yml
```suggestion
  - conda env create -q -n test-env --file qiime2-2020.6-py36-linux-conda.yml
```

2020-08-21 00:04 UTC, patrickimran commented on .travis.yml
>    - conda env create -q -n test-env --file qiime2-latest-py36-linux-conda.yml
good catch

2020-08-21 18:37 UTC, ElDeveloper commented on q2_mlab/learningtask.py
> +LogisticRegressionLasso = ModelFactory.get_model(LogisticRegression,
Just add a note about algorithm asymmetries

2020-08-21 18:39 UTC, ElDeveloper commented on q2_mlab/tests/test_parameters.py
> +    n_samples, n_features, task=Task.REGRESSION, count=500
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html

2020-08-21 18:42 UTC, ElDeveloper requested changes

2020-08-21 18:42 UTC, ElDeveloper commented on q2_mlab/tests/test_parameters.py
> +    def setUp(self):
Consider as a setUpClass method so that this gets only called once.

2020-08-21 22:49 UTC, gwarmstrong commented on q2_mlab/learningtask.py
> +
```suggestion

# scikit-learn has some asymmetries between classifiers and regressors, e.g.,
# `Lasso`'s classification equivalent is `LogisticRegression` with
# `penalty='l1'`. You can use ModelFactory.get_model to create Estimator
# classes that set specific parameters.
```

2020-08-25 16:07 UTC, ElDeveloper commented
@patrickimran @gwarmstrong is this ready to be merged?

2020-08-25 16:22 UTC, gwarmstrong commented
LGTM

2020-08-26 01:20 UTC, merged